name: build-exe

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # =========================
      # SETUP PYTHON
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # =========================
      # INSTALL DEPENDENCIES
      # =========================
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # =========================
      # BUILD EXE
      # =========================
      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller `
          --noconfirm `
          --clean `
          --onefile `
          --add-data "models;models" `
          main.py

      # =========================
      # UPLOAD ARTIFACT
      # =========================
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ai-pool-exe
          path: dist/
